version: '3'

services:
  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./app-laravel:/app-laravel
    links:
      - php
    networks:
      - app-network

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./app-laravel:/app-laravel
    working_dir: /app-laravel
    depends_on:
      - rabbitmq  # Laravel powinien uruchomić się po RabbitMQ
    networks:
      - app-network
    environment:
      - QUEUE_CONNECTION=rabbitmq
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest

  db:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: notatki_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pg-admin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - app-network

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    ports:
      - "5672:5672"  # Port dla komunikacji RabbitMQ
      - "15672:15672" # Panel administracyjny RabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app-network

  worker:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./app-laravel:/app-laravel
    working_dir: /app-laravel
    command: php artisan queue:work --tries=3 --timeout=90
    depends_on:
      - php
      - rabbitmq
    networks:
      - app-network

networks:
  app-network:

volumes:
  db-data:
